### ISSUE TITLE
Regular expressions to access to HTML element (help!!)

### ISSUE THREAD

**Issue by davidaldan** [gidlov/copycat#5]
When I want to access for example:

```
<div class="user-content">
       <h1>Test</h1>
</div>
```
I used this:

`'telefono' => '/class="user-content">.*?>(.*?)</ms',
`

This's ok.

But when I can to access to this:

```
<div class="user-content">
       <div>
              <h1>Test</h1>
       </div>
</div>
```

What is the corret Regular expressions to use, Thanks for help.

**Comment by gidlov** [comment]
I do not know if I fully understand the question. If there is something
wrong in the expression, you may need to escape the hyphen.

Please enclose some code and error messages / answers and we will see if I
can assist you.


Den 23 maj 2017 23:55 skrev "davidaldan" <notifications@github.com>:

When I want to access for example:

<div class="user-content">
       <h1>Test</h1>
</div>

I used this:

'telefono' => '/class="user-content">.*?>(.*?)</ms',

This's ok.

But when I can to access to this:

<div class="user-content">
       <div>
              <h1>Test</h1>
       </div>
</div>

What is the corret Regular expressions to use, Thanks for help.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gidlov/copycat/issues/5>, or mute the thread
